version: "3"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
  database:
    image: mdillon/postgis
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-rtm}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-rtm}
      - POSTGRES_DB=${POSTGRES_DB:-rtm}
  rtm-web:
    image: ${DOCKER_IMAGE_NAME:-uninfo/rtm}:${TAG:-latest}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DEBUG=${DEBUG:-true}
      - COMPRESS_ENABLED=${COMPRESS_ENABLED:-false}
      - COMPRESS_OFFLINE=${COMPRESS_OFFLINE:-false}
      - DEFAULT_DATABASE=${DEFAULT_DATABASE:-postgresql://rtm:rtm@database:5432/rtm}
      - REDIS_HOST=${REDIS_HOST:-redis}
    links:
      - redis
      - database
    depends_on:
      - redis
      - database
