#!/bin/sh

set -o errexit
set -o nounset

python ./manage.py migrate
python ./manage.py collectstatic --noinput

/usr/local/bin/gunicorn rtm.wsgi --bind 0.0.0.0:8000 --log-level=debug --access-logfile=./gunicorn.access --error-logfile=./gunicorn.errors --capture-output --chdir=/app
