# Generated by Django 2.2.5 on 2019-10-10 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0056_auto_20190926_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollquestion',
            name='sdgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, choices=[(1, 'No Poverty'), (2, 'Zero Hunger'), (3, 'Good Health and Well-Being'), (4, 'Quality Education'), (5, 'Gender Equality'), (6, 'Clean Water and Sanitation'), (7, 'Affordable And Clean Energy'), (8, 'Decent Work and Economic Growth'), (9, 'Industry, Innovation and Infrastructure'), (10, 'Reduced Inequalities'), (11, 'Sustainable Cities and Communities'), (12, 'Responsible Production and Consumption'), (13, 'Climate Action'), (14, 'Life Below Water'), (15, 'Life On Land'), (16, 'Peace, Justice and Strong Institutions'), (17, 'Partnerships for the Goals')], null=True), default=[1], size=None),
            preserve_default=False,
        ),
    ]
