# Generated by Django 2.2.5 on 2019-10-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("channels", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="channelmonthlystats",
            name="error_count",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        )
    ]
