# Generated by Django 2.2.5 on 2019-10-15 13:52

from django.db import migrations


def tag_create(apps, schema_editor):
    """
    create tag for autocomplete resorce in forms.
    """
    Tag = apps.get_model("taggit", "Tag")

    if Tag.objects.all().count() < 1:
        Tag.objects.create(name="life")
        print("created initial tag for Taggit")


class Migration(migrations.Migration):

    dependencies = [("flowhub", "0003_auto_20191015_0259")]

    operations = [migrations.RunPython(tag_create)]
