# Generated by Django 2.2.5 on 2019-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("flowhub", "0004_auto_20191015_1052")]

    operations = [
        migrations.AddField(
            model_name="flow", name="stars", field=models.IntegerField(default=0)
        )
    ]
