# Generated by Django 2.2.5 on 2020-02-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worldmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgcountrycode',
            name='org_country_code',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
