# Generated by Django 2.2.5 on 2020-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0058_poll_poll_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll", name="title", field=models.TextField(help_text="The title for this Poll"),
        ),
    ]
