# Generated by Django 2.2.5 on 2020-01-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls_global", "0003_auto_20200116_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollglobalsurveys", name="percent_compability", field=models.FloatField(blank=True, null=True),
        ),
    ]
