# Generated by Django 2.2.5 on 2019-12-06 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0058_poll_poll_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PollGlobal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is active, use this instead of deleting')),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('modified_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was last modified')),
                ('poll_date', models.DateField(help_text='The date to display for this survey.')),
                ('poll_end_date', models.DateField(help_text='The date to display for this survey.', null=True)),
                ('title', models.CharField(help_text='The title for this survey.', max_length=255)),
                ('description', models.TextField(help_text='THe description for this survey.', null=True)),
                ('created_by', models.ForeignKey(help_text='The user which originally created this item', on_delete=django.db.models.deletion.PROTECT, related_name='polls_global_pollglobal_creations', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(help_text='The user which last modified this item', on_delete=django.db.models.deletion.PROTECT, related_name='polls_global_pollglobal_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollGlobalSurveys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_joined', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, help_text='When this item was originally created')),
                ('poll_global', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polls_global', to='polls_global.PollGlobal')),
                ('poll_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polls_global', to='polls.Poll')),
            ],
            options={
                'unique_together': {('poll_global', 'poll_local')},
            },
        ),
    ]
