# Generated by Django 2.2.5 on 2019-12-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_global', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollglobal',
            name='poll_date',
            field=models.DateField(help_text='The date to display for this survey.'),
        ),
        migrations.AlterField(
            model_name='pollglobal',
            name='poll_end_date',
            field=models.DateField(help_text='The date to display for this survey.', null=True),
        ),
    ]
